title: FastBuilder Wiki
description: A compact community wiki.
baseurl: "/taof"
url: "https://aquabridge.github.io"
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
